language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -r requirements/test.txt
script:
  "if (( ${TRAVIS_PYTHON_VERSION%%.*} >= 3 )) && (( ${TRAVIS_PYTHON_VERSION: -1:1} >= 6 )); then make; else make test; fi"