language: python
python:
  - "3.8"
  - "3.9"
before_install:
  - python -m pip install --upgrade pip
install:
  - pip install -r requirements/test.txt --use-deprecated=legacy-resolver
script:
  - "make"